# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29bba32796c70dbebbeed680a8b0d917f0add7cd28368ef4b820c72dd03c72d638ce97c2bf10aa64eafca3cf4b6d07bda9bddf822930d1a5dd19e603f3499f9f

test:
  secret_key_base: ffa9d9e3ddaeb52c1bd849016b8b97791c6e8f5ff31ead17522fc88287bf6e4dda42aa13766e41aec42f86e9922eaebab5c5db040a668f9abc69f4585cf34e49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
